### ISSUE TITLE
Is there a way to avoid global variables for compile time data structures?

### ISSUE THREAD

**Issue by 0xadeeb** [softdevteam/grmtools#397]
As of now, compile time data structures like symbol table, type table, current function/class that is being parsed should be stored wrapped in a mutex (or refcell if using threadlocal! macro) and be declared as a global variable which has to be unlocked and accessed by each rule in the grammar. Is there a way to create these data structures in the main function and pass it's reference to the parser or any other way to avoid using global variables, if there is what is the best way to do it?

**Comment by ltratt** [comment]
I think you might want [`%parse-param`](https://softdevteam.github.io/grmtools/latest_release/book/actioncode.html#additional-parse-parameter) which allows  to pass arbitrary data of an arbitrary type to the parser. Depending on your use case, that might best be a `struct` or an `enum`.

**Comment by 0xadeeb** [comment]
So if I need to send symbol table and type table to the parser, I should create another struct (let's call it ParserState) with both these data structures and use `%parse-param p: &ParserState` in the `.y` file and I don't need to define this in variable anywhere like in main function or so. If that's the case is variable `p` defined in the parser generated by `lrpar` and dropped after the parsing?

**Comment by ltratt** [comment]
https://github.com/softdevteam/grmtools/blob/master/lrpar/cttests/src/parseparam.test might help explain how to use it.

**Comment by ratmice** [comment]
You can also pass a tuple to `%parse-param`, so that is possible if it is inconvenient to make a struct wrapping up all of your parameters.  I seem to recall there are some limitations on the parameters like being copy or shared references for reference types.  (But it has been long enough that i'm not totally sure).  So if you do need something like a mutable symbol table, you may need interior mutability.

There is also a mention of the tuple aspects here in the yacc compatibility section:
https://softdevteam.github.io/grmtools/master/book/yacccompatibility.html

**Comment by 0xadeeb** [comment]
Thanks for the quick replies, I could successfully do what I wanted to do. I'll close this issue now.
