### ISSUE TITLE
lrlex: match beginning of line

### ISSUE THREAD

**Issue by liluyue** [softdevteam/grmtools#449]
I am working on a markdown parser. Many of its tags, such as "#", match from the beginning of the line. **^** does not work in lrlex, and **(? m) ^** also does not work

**Comment by ltratt** [comment]
lrlex is, intentionally, fairly simplistic. If you want to do a whitespace sensitive language (e.g. one that requires "start of line"), particularly one with some unusual rules such as markdown's, you'll want to write a hand-written lexer. The good news is that lrpar can happily work with a hand-written parser: see https://softdevteam.github.io/grmtools/master/book/manuallexer.html.

**Comment by ratmice** [comment]
I haven't tried to see what causes it not to work, but I'm a little bit suprised because the default for [RegexBuilder::multi_line](https://docs.rs/regex/1.8.4/regex/struct.RegexBuilder.html#method.multi_line) within lrlex is *true*.  But wanted to note that perhaps there are other regex options that affect the behavior.

It is worth noting that since 1.9.x regex has added [RegexBuilder::crlf](https://docs.rs/regex/latest/regex/struct.RegexBuilder.html#method.crlf), so I'm curious if perhaps you are testing with crlf data?

Anyhow besides a manual lexer, perhaps there are options to `RegexBuilder`, which could be added/supported also?

**Comment by liluyue** [comment]
> I haven't tried to see what causes it not to work, but I'm a little bit suprised because the default for [RegexBuilder::multi_line](https://docs.rs/regex/1.8.4/regex/struct.RegexBuilder.html#method.multi_line) within lrlex is _true_. But wanted to note that perhaps there are other regex options that affect the behavior.
> 
> It is worth noting that since 1.9.x regex has added [RegexBuilder::crlf](https://docs.rs/regex/latest/regex/struct.RegexBuilder.html#method.crlf), so I'm curious if perhaps you are testing with crlf data? Perhaps we could add support for that option in [CTLexerBuilder](https://softdevteam.github.io/grmtools/master/api/lrlex/struct.CTLexerBuilder.html).
> 
> Anyhow besides a manual lexer, perhaps there are options to `RegexBuilder`, which could changed to make this work?

because that String truncation causes loss of row information: 
<img width="1432" alt="截屏2024-05-13 13 07 56" src="https://github.com/softdevteam/grmtools/assets/19216288/8fe7a9b7-c629-4a41-b4c5-471893da6ac3">
<img width="1566" alt="截屏2024-05-13 13 08 22" src="https://github.com/softdevteam/grmtools/assets/19216288/0bdf57b9-7589-4886-b64b-f98c2617ab06">

**Comment by ratmice** [comment]
Ahh, indeed the `\A` in your screenshot, and beginning to recall how the algorithm used in lrlex behaves it now makes sense why this doesn't just work already.

So indeed it seems like a manual lexer might be the only way to achieve this.
